all:
	(cd MPCFcore/makefiles; make all)
	(cd MPCFnode/makefiles; make all)
	(cd MPCFcluster/makefiles; make all)

clean:
	(cd MPCFcore/makefiles; make clean)
	(cd MPCFnode/makefiles; make clean)
	(cd MPCFcluster/makefiles; make clean)
