SHELL := /bin/bash

CC ?= gcc
LD ?= gcc

# core
bs ?= 16
ap ?= float
weps ?= 1e-6
precdiv ?= 0
sse ?= 1
avx ?= 0
omp ?= 1
align ?= 16
bgq ?= 0

# +node
hdf ?= 1
vtk ?= 1
numa ?= 0
cvt ?= 0
nthreads ?= 24

# +cluster
fftw ?= 1
#

CPPFLAGS+= $(extra)

ifeq "$(ap)" "float"
        CPPFLAGS += -D_FLOAT_PRECISION_
endif

ifeq "$(config)" "release"
	ifeq "$(CC)" "icc"
		OPTFLAGS+= -DNDEBUG -O3 -xHOST  -ip -ansi-alias -fno-fnalias -inline-level=1
		ifeq "$(ap)" "float"
			CPPFLAGS += -fp-model precise 
		else
			CPPFLAGS += -fast
		endif
	else
		ifeq "$(bgq)" "1"
			OPTFLAGS += -O3 -qarch=qp -qtune=qp -qhot -qstrict -qsource -qlist -qreport -DNDEBUG
		else
			OPTFLAGS += -O3 -fno-expensive-optimizations -falign-functions=16 -DNDEBUG #one can leave out falign to the default of O2 level  which is machine-dependent
		endif
	endif
else
	CPPFLAGS += -g 
endif

ifeq "$(CC)" "icc"
	ifeq "$(avx)" "1"
		CPPFLAGS += -xAVX -D_AVX_
	endif
	CPPFLAGS += -Wbrief -wd18000 -diag-disable remark
else
	ifeq "$(avx)" "1"
		CPPFLAGS += -mavx -D_AVX_
	endif	
endif

CPPFLAGS += -Wno-deprecated 

ifeq "$(cvt)" "1"
	CPPFLAGS += -D_USE_CVT_
endif

ifeq "$(precdiv)" "1"
CPPFLAGS += -D_PREC_DIV_
endif 

ifeq "$(precdiv)" "-1"
	CPPFLAGS += -D_PREC_DIV_NONE_
	ifeq "$(CC)" "icc"
		#OPTFLAGS += -ipo
	endif
endif 

ifeq "$(ap)" "float"
	CPPFLAGS += -D_SP_COMP_
endif 

ifeq "$(sse)" "1"
	CPPFLAGS += -D_SSE_ -msse -msse2
endif

ifeq "$(omp)" "1"
	ifeq "$(CC)" "icc"
		CPPFLAGS += -openmp	
		OPTFLAGS += -openmp
	else
		ifeq "$(bgq)" "1"
			CPPFLAGS += -qsmp=omp
			OPTFLAGS += -qsmp=omp
		else
			CPPFLAGS += -fopenmp
			OPTFLAGS += -fopenmp
		endif
	endif	
endif

######

vtk-inc ?=/usr/local/include/vtk-5.2/ 
vtk-lib ?=/usr/local/lib/vtk-5.2/ 
numa-inc ?=/cluster/work/infk/diegor/numactl-2.0.8-rc4 
numa-lib ?=/cluster/work/infk/diegor/numactl-2.0.8-rc4
hdf-inc ?=.
hdf-lib ?=.

ifneq "$(findstring rosa,$(shell hostname))" ""
	ifeq "$(CC)" "cc"
		LIBS += -dynamic
	endif
endif

ifneq "$(findstring todi,$(shell hostname))" ""
	ifeq "$(CC)" "cc"
		LIBS += -dynamic
	endif
endif

ifeq "$(shell hostname)" "reynolds.inf.ethz.ch"
	vtk-inc =/usr/local/include/vtk-5.6/
	vtk-lib =/usr/local/lib/vtk-5.6/
endif

ifeq "$(shell hostname)" "silvio"
	vtk-inc = /usr/include/vtk-5.6/
	vtk-lib = /usr/lib/vtk-5.6/
#	hdf-inc = /home/hbabak/hdf5-1.8.8_gcc_serial/include/
#	hdf-lib = /home/hbabak/hdf5-1.8.8_gcc_serial/lib/
        hdf-inc = /home/hbabak/hdf5-1.8.8_gcc/include/
        hdf-lib = /home/hbabak/hdf5-1.8.8_gcc/lib/
	numa-inc = /home/hbabak/numactl-2.0.7/include/
	numa-lib = /home/hbabak/numactl-2.0.7/
endif

ifneq "$(findstring brutus,$(shell hostname))" ""
	vtk-inc = /cluster/work/infk/cconti/VTK5.8_gcc/include/vtk-5.8/
	vtk-lib = /cluster/work/infk/cconti/VTK5.8_gcc/lib/vtk-5.8/
	#ifneq "$(findstring mpi,$(CC))" ""
	#     hdf-inc = /cluster/apps/hdf5/1.8.8_pic/x86_64/openmpi_1.6.1/gcc_4.7.0/include/
	#     hdf-lib = /cluster/apps/hdf5/1.8.8_pic/x86_64/openmpi_1.6.1/gcc_4.7.0/lib/
	#else
		hdf-inc = /cluster/work/infk/hbabak/apps/hdf5-1.8.8_gcc_serial/include/
		hdf-lib = /cluster/work/infk/hbabak/apps/hdf5-1.8.8_gcc_serial/lib/
	#endif
	numa-inc = /cluster/work/infk/hbabak/numactl-2.0.7/include/
	numa-lib = /cluster/work/infk/hbabak/numactl-2.0.7/
endif

ifneq "$(findstring rosa,$(shell hostname))" ""
        vtk-inc = /users/petrosk/VTK/include/vtk-5.8/
        vtk-lib = /users/petrosk/VTK/lib/vtk-5.8/
	#ifeq "$(CC)" "icc"
	#	hdf-inc = /users/petrosk/hdf5-1.8.8_icc_serial/include/
	#	hdf-lib = /users/petrosk/hdf5-1.8.8_icc_serial/lib/
	#else
	#	hdf-inc = /users/petrosk/hdf5-1.8.8_gcc_serial/include/
	#	hdf-lib = /users/petrosk/hdf5-1.8.8_gcc_serial/lib/
	#endif

	ifeq "$(CC)" "icc"	
	     hdf-inc = /opt/cray/hdf5-parallel/1.8.8/intel/120/include/#/users/petrosk/hdf5-1.8.8/include/
     	     hdf-lib = /opt/cray/hdf5-parallel/1.8.8/intel/120/lib/#/users/petrosk/hdf5-1.8.8/lib/
	else
             hdf-inc = /users/petrosk/hdf5-1.8.8_gcc/include/
             hdf-lib = /users/petrosk/hdf5-1.8.8_gcc/lib/
	endif

	numa-inc = /users/petrosk/numactl-2.0.7/
	numa-lib = /users/petrosk/numactl-2.0.7/lib64/
endif

ifneq "$(findstring todi,$(shell hostname))" ""
        vtk-inc = /users/petrosk/VTK/include/vtk-5.8/
        vtk-lib = /users/petrosk/VTK/lib/vtk-5.8/
	ifeq "$(CC)" "icc"
		hdf-inc = /users/petrosk/hdf5-1.8.8_icc_serial/include/
		hdf-lib = /users/petrosk/hdf5-1.8.8_icc_serial/lib/
	else
		hdf-inc = /users/petrosk/hdf5-1.8.8_gcc_serial/include/
		hdf-lib = /users/petrosk/hdf5-1.8.8_gcc_serial/lib/
	endif
	numa-inc = /users/petrosk/numactl-2.0.7/
	numa-lib = /users/petrosk/numactl-2.0.7/lib64/
endif

CPPFLAGS += -D_ALIGNBYTES_=$(align) -D_BLOCKSIZE_=$(bs) -D_BLOCKSIZEX_=$(bs) -D_BLOCKSIZEY_=$(bs) -D_BLOCKSIZEZ_=$(bs) -DWENOEPS=$(weps) -DNTHREADS=$(nthreads)
CPPFLAGS += -I../../../Cubism/source/ -I../source -I../../MPCFcore/source/ -I/usr/local/include/

ifeq "$(hdf)" "1"
	CPPFLAGS += -I$(hdf-inc) -D_USE_HDF_
	LIBS += -L$(hdf-lib) -lhdf5
endif

CPPFLAGS +=  -I$(hdf-inc)

LIBS += -lstdc++ -lm -lrt

ifeq "$(bgq)" "1"
	LIBS += /gpfs/DDNgpfs1/walkup/mpi_trace/bgq/lib/libmpihpm.a \
			/bgsys/drivers/ppcfloor/bgpm/lib/libbgpm.a \
			-L/bgsys/drivers/ppcfloor/spi/lib -lSPI_upci_cnk
endif

ifeq "$(vtk)" "1"
	CPPFLAGS += -I$(vtk-inc) -D_USE_VTK_

	LIBS += -L$(vtk-lib) \
		-lvtkVolumeRendering \
		-lvtkRendering \
		-lvtkIO \
		-lvtkGenericFiltering \
		-lvtkGraphics \
		-lvtkImaging \
		-lvtkFiltering \
		-lvtkCommon \
		-lvtkftgl \
		-lvtkDICOMParser \
		-lvtksys \
		-lvtkexoIIc \
		-lvtkNetCDF \
		-lvtkNetCDF_cxx \
		-lvtkmetaio \
		-lvtksqlite \
		-lvtkverdict \
		-lvtkexpat \
		-lvtktiff \
		-lvtkpng \
		-lvtkjpeg \
		-lvtkzlib \
		-lvtkHybrid \
		-lvtkfreetype

	ifneq "$(findstring brutus,$(shell hostname))" ""
		LIBS+= -lvtkParallel -lVPIC -lCosmo
	endif
endif

ifeq "$(numa)" "1"
	CPPFLAGS += -D_USE_NUMA_ -I$(numa-inc)
	LIBS += -L$(numa-lib) -lnuma
endif

#LIBS += -L/usr/local/lib/ -lfreesteam